version: "3.8"

services:
  blog:
    image: node:17.3.0-bullseye-slim
    working_dir: /blog
    volumes:
      - ./:/blog:cached
      - next:/blog/.next
      - node_modules:/blog/node_modules
    command: sh -c "npm install && npm run dev"
    ports:
      - ${NODE_PORT:-3000}:3000

volumes:
  next:
  node_modules:
