version: "3.8"

services:
  blog:
    image: blog-dev:2.1.0
    build:
      context: dockerfiles
    working_dir: /blog
    volumes:
      - ./:/blog:cached
      - dist:/blog/dist
      - node_modules:/blog/node_modules
      - yarn-cache:/usr/local/share/.cache/yarn/v6
    command: sh -c "yarn && yarn dev"
    ports:
      - 3000:3000

volumes:
  dist:
  node_modules:
  yarn-cache:
