version: "3.8"

services:
  blog:
    image: blog-dev:2.0.0
    build:
      context: dockerfiles
    working_dir: /blog
    volumes:
      - ./:/blog:cached
      - next:/blog/.next
      - node_modules:/blog/node_modules
      - yarn-cache:/usr/local/share/.cache/yarn/v6
    command: sh -c "yarn && yarn dev"
    env_file:
      - .env
    # please set exposed ports by using docker-compose.override.yml or other solutions
    # ports:
      # - 3000:3000

volumes:
  next:
  node_modules:
  yarn-cache:
