version: "3.8"

services:
  blog:
    image: node:17.3.0-bullseye-slim
    working_dir: /blog
    volumes:
      - ./:/blog:cached
      - next:/blog/.next
      - node_modules:/blog/node_modules
      - yarn-cache:/usr/local/share/.cache/yarn/v6
    command: sh -c "yarn && yarn dev"
    ports:
      - 3000:3000
    env_file:
      - .env.development.local

volumes:
  next:
    driver: local
  node_modules:
    driver: local
  yarn-cache:
    driver: local
