version: "3.8"

services:
  blog:
    image: blog-dev:1.0.0
    build:
      context: dockerfiles
    working_dir: /blog
    volumes:
      - ./:/blog:cached
      - next:/blog/.next
      - node_modules:/blog/node_modules
      - yarn-cache:/usr/local/share/.cache/yarn/v6
    command: sh -c "yarn && yarn dev"
    ports:
      - ${NODE_PORT:-3000}:3000
    env_file:
      - .env.development.local

volumes:
  next:
  node_modules:
  yarn-cache:
