version: "3.8"

services:
  blog:
    image: rusconn/blog-dev:1.0.0
    build:
      context: .devcontainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "yarn && sleep infinity"
